### ISSUE TITLE
/assets/text/serial_output.txt is missing

### ISSUE THREAD

**Issue by magn2o** [d-jahren/d-jahren.github.io#1]
I've gone down this rabbit hole, extracting certs from a Pace 5268. I'm currently debugging some serial comm issues and noticed that the serial_output.txt is linked to from your blog, but it doesn't seem to exist. 

Additionally, your images show *4* pins on the UART which you've soldered to, but only 3 are documented (TX, RX, GND).

Would you also happen to know which firmware your particular modem was on? I've successfully downgraded this particular unit to 10.7.0.530220, and while the UART appears to be active, nothing readable is returned.

**Comment by d-jahren** [comment]
As far as the hardware goes, the 3 documented pins should be all you need to get a shell. I don't think I have the serial_output file anymore, so I'll make sure to update that, but it was pretty much just a bog standard embedded linux boot sequence. IIRC, I think I was on firmware 10.5.3.
